apiVersion: apps/v1
kind: Deployment
metadata:
  name: senagae-fe-deployment-blue
spec:
  selector:
    matchLabels:
      type: frontend
      ver: test
      deployment: blue
  replicas: 4
  strategy:
    type: RollingUpdate
  minReadySeconds: 10
  template:
    metadata:
      labels:
        type: frontend
        ver: test
        deployment: blue
    spec:
      containers:
        - name: senagae-fe-blue
          image: senagae/frontend:1.1
          readinessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 20
            periodSeconds: 10
            successThreshold: 4
          livenessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 20
            periodSeconds: 10
      terminationGracePeriodSeconds: 0