apiVersion: apps/v1
kind: Deployment
metadata:
  name: senagae-be-deployment-color
spec:
  selector:
    matchLabels:
      type: backend
      ver: latest
      deployment: color
  replicas: 4
  strategy:
    type: RollingUpdate
  minReadySeconds: 10
  template:
    metadata:
      labels:
        type: backend
        ver: latest
        deployment: color
    spec:
      containers:
        - name: senagae-be-color
          image: senagae/backend:latest
          readinessProbe:
            httpGet:
              path: /test
              port: 8080
            initialDelaySeconds: 20
            periodSeconds: 10
            successThreshold: 4
          livenessProbe:
            httpGet:
              path: /test
              port: 8080
            initialDelaySeconds: 20
            periodSeconds: 10
      terminationGracePeriodSeconds: 0